development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: nlims
  suffix: repo
  username: root
  password: password

test:
  <<: *development
  suffix: test

production:
  <<: *development
  protocol: 'http'
