source:
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 
  database: eid_vl
  username: root
  password: password

destination: http://localhost:3014/create_hl7_order
