source:
  host: 'localhost'
  port: '3232'
  database: 'eid_vl'
  username: 'root'
  password: 'password'
  testing_lab: 'Queen Elizabeth Central Hospital'

target: 
  host:                           '192.168.43.50'
  port:                           '3009'
  prefix:                         '/api/v1/'
  protocol:                       'http'
  app_name:                       'migrator'
  token:                          'XEFH6384'
  username:                       'dev'
  password:                       'dev'